#!/usr/bin/env node

/**
 * Version generation script
 *
 * Reads package.json and generates cli/version.ts with the version information.
 * This ensures the version is available for both development and bundled builds.
 *
 * Also embeds git commit hash and build time for artifact traceability.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import process from "node:process";

function getGitCommit() {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf-8" }).trim();
  } catch {
    // In environments without git (e.g., extracted from tarball)
    return "unknown";
  }
}

try {
  // Read version from package.json
  const packageJson = JSON.parse(readFileSync("package.json", "utf-8"));
  const version = packageJson.version;
  const commit = getGitCommit();
  const buildTime = new Date().toISOString();

  // Generate version.ts content
  const versionFileContent = `// Auto-generated file - do not edit manually
// This file is generated by scripts/generate-version.js
export const VERSION = "${version}";
export const COMMIT = "${commit}";
export const BUILD_TIME = "${buildTime}";
`;

  // Write version.ts file
  writeFileSync("cli/version.ts", versionFileContent);

  console.log(`✅ Generated cli/version.ts with version: ${version}, commit: ${commit}, buildTime: ${buildTime}`);
} catch (error) {
  console.error("❌ Failed to generate version.ts:", error.message);
  process.exit(1);
}
